config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :categories, only: [:index, :new, :create]

  resources :posts do 
    resources :comments 
  end

end

app/models/categories_post.rb
class CategoriesPost < ActiveRecord::Base
  belongs_to :post 
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categories_posts
  has_many :posts, through: :categories_posts

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

  validates :content, presence: true, length: {minimum: 5}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  has_many :comments
  has_many :categories_posts
  has_many :categories, through: :categories_posts
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts
  has_many :comments
  
  has_secure_password validations: false

  validates :name, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save!
      redirect_to categories_path
    else
      render :new
    end
  end

  private 

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:content))
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.user = current_user

    if post.save!
      redirect_to posts_path
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, category_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:name])

    if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        flash[:notice] = "You've logged in!"
        redirect_to root_path
    else
      redirect_to login_path
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private 

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<% if category.name == 'Category1' %>
  <span class='badge alert-danger'>
<% elsif category.name == 'Category2' %>
  <span class='badge alert-success'>
<% elsif category.name == 'Category3' %>
  <span class='badge alert-info'>
<% elsif category.name == 'Category4' %>
  <span class='badge alert-warning'>
<% elsif category.name == 'Category5' %>
  <span class='badge progress-bar-info'>
<% end %>
  <%= link_to category.name, categories_path %>
</span>

app/views/categories/index.html.erb
<%= render 'shared/title', title: 'All Categories'%>

<h6><%= link_to '(Create New Category)', new_category_path %></h6>

<% @categories.each do |category| %>
<div class='row'>
  <div class='well col-md-6'>
    <p><%= link_to category.name, categories_path %></p>
  </div>  
</div>
<% end %>

app/views/categories/new.html.erb
<%= render 'shared/title', title: "Create New Category"%>

<div class="well col-md-6">
  <%= form_for @category do |c| %>
    <div class="form-group">
      <%= c.label :category_name %>
      <br>
      <%= c.text_field :name %>
    </div>
    <%= c.submit 'Create Category', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Board", root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to 'New Post', new_post_path %></li>
          <li><%= link_to 'Categories', categories_path %></li>
        <% else %>
          <li><%= link_to 'Register', register_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav"><!--<ul class="nav navbar-nav navbar-right">-->
        <% if logged_in? %>
          <li class="dropdown">
            <%= link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown' do %>
            <%= current_user.name %> <span class='caret'></span>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to 'User Profile', user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Logout', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Board</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/_post.html.erb
  <div class="row">
    <div class="well col-md-6">
      <%= render partial: "categories/category", collection: post.categories %>
      <p>
        <h4><%= post.title %></h4>
      </p>
      <p>
        <%= post.content %>
      </p>
      <br>
      <span>
        <%= link_to "show comments", post_path(post) %>
      </span>
    </div>
  </div>

app/views/posts/index.html.erb
<%= render 'shared/title', title: 'Post List'%>
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/title', title: 'New Post'%>
<hr>
<div class="well col-md-12">
  <%= form_for @post do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <br>
      <%= f.text_field :title %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <br>
      <%= f.text_area :content, rows: 5 %>
    </div>
    <div class="form-group">
      <%= f.label :categories %>
      <br>
      <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :name) do |cbox|%>
      <%= cbox.label(class: "checkbox-inline") { cbox.check_box(class: "checkbox") + cbox.text } %>
      <% end %>
      <p></p><p><%= link_to '(Create New Category)', new_category_path %></p>
    </div>

  <br>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>
  <% end %>
</div>

<%= link_to 'Back to Post List', posts_path %>

app/views/posts/show.html.erb
<%= render 'shared/title', title: "#{@post.title}"%>

<div class="row">
  <div class="col-md-8 well">
    <%= render partial: "categories/category", collection: @post.categories %>
    <h3><%= @post.title %></h3>
    <p>
      <%= @post.content %>
    </p>
    <br>
    <small>posted by </small><%= " #{@post.user.name}" %><small> at </small><%= " #{@post.updated_at}" %>
  </div>
</div>

<h4>All Comments:</h4>

<% @post.comments.each do |comment| %>
  <div class="row">
    <div class="col-md-6 well">
      <p>
        <%= comment.content %>
      </p>
      <br>
      <small>commented by </small><%= "#{comment.user.name}" %>
    </div>
  </div>
<% end %>
<p> </p><hr><p> </p>
<% if logged_in? %>

  <h4>Leave a comment:</h4>
  <%= form_for [@post, @comment] do |f| %>
    <div class="row">
      <%= f.text_area :content, rows: 3, class: 'col-md-4' %>
      <div class="col-md-2">
        <%= f.submit 'Create Comment', class: 'btn btn-primary' %>
      </div>
    </div>
    <br>
  <% end %>

<% end %>

<hr>

<div class="row">
  <%= link_to 'go back to all posts', posts_path %>
</div>

app/views/shared/_title.html.erb
<h3><%= title %></h3>
</hr>

app/views/users/new.html.erb
<h2>Register</h2>

<div class="well col-md-6">
  <%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password%>
  </div>
  <br>
  <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render 'shared/title', title: "#{@user.name}'s activities"%>

<h4><%= current_user.name %>'s posts:</h4>

<% @user.posts.each do |post| %>

<div class="row">
  <div class="col-md-8 well">
    <h3><%= post.title %></h3>
    <p>
      <%= post.content %>
    </p>
    <br>
    <small>posted by </small><%= " #{post.user.name}" %>
  </div>
</div>

<% end %>
<hr>
<h4><%= current_user.name %>'s comments:</h4>

<% @user.comments.each do |comment| %>
  <div class="row">
    <div class="col-md-6 well">
      <p>
        <%= comment.content %>
      </p>
      <br>
      <small>commented by </small><%= "#{comment.user.name}" %>
    </div>
  </div>
<% end %>

<%= link_to 'Back', root_path %>